/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin.packages'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminPackagesNewRouteImport } from './routes/_authenticated/admin.packages.new'
import { Route as AuthenticatedAdminPackagesIdEditRouteImport } from './routes/_authenticated/admin.packages.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesNewRoute =
  AuthenticatedAdminPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)
const AuthenticatedAdminPackagesIdEditRoute =
  AuthenticatedAdminPackagesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminPackagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/packages/$id/edit': typeof AuthenticatedAdminPackagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/packages/$id/edit': typeof AuthenticatedAdminPackagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/packages': typeof PackagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRouteWithChildren
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/_authenticated/admin/packages/$id/edit': typeof AuthenticatedAdminPackagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/packages'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/packages/$slug'
    | '/admin/categories'
    | '/admin/packages'
    | '/admin/tags'
    | '/admin/'
    | '/admin/packages/new'
    | '/admin/packages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/packages'
    | '/reset-password'
    | '/sitemap.xml'
    | '/packages/$slug'
    | '/admin/categories'
    | '/admin/packages'
    | '/admin/tags'
    | '/admin'
    | '/admin/packages/new'
    | '/admin/packages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/packages'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/packages/$slug'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/packages/new'
    | '/_authenticated/admin/packages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/new': {
      id: '/_authenticated/admin/packages/new'
      path: '/new'
      fullPath: '/admin/packages/new'
      preLoaderRoute: typeof AuthenticatedAdminPackagesNewRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
    '/_authenticated/admin/packages/$id/edit': {
      id: '/_authenticated/admin/packages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/packages/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminPackagesRoute
    }
  }
}

interface AuthenticatedAdminPackagesRouteChildren {
  AuthenticatedAdminPackagesNewRoute: typeof AuthenticatedAdminPackagesNewRoute
  AuthenticatedAdminPackagesIdEditRoute: typeof AuthenticatedAdminPackagesIdEditRoute
}

const AuthenticatedAdminPackagesRouteChildren: AuthenticatedAdminPackagesRouteChildren =
  {
    AuthenticatedAdminPackagesNewRoute: AuthenticatedAdminPackagesNewRoute,
    AuthenticatedAdminPackagesIdEditRoute:
      AuthenticatedAdminPackagesIdEditRoute,
  }

const AuthenticatedAdminPackagesRouteWithChildren =
  AuthenticatedAdminPackagesRoute._addFileChildren(
    AuthenticatedAdminPackagesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRouteWithChildren
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRouteWithChildren,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PackagesRoute: PackagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
